[project]
name = "gamelog"
version = "1.0.0"
description = "A utility to keep track of board games scores"
requires-python = ">=3.12"
dependencies = [
    "PySide6",
    "PyQt5",
]
[project.scripts]
gamelog = "gamelog.pyw:__main__"
